### ISSUE TITLE
albert 用不了。。。

### ISSUE THREAD

**Issue by illcat** [Vincent131499/Multi_Label_Classifier_finetune#2]

**Comment by Vincent131499** [comment]
Hello，感谢关注，Albert适配已添加，请重新查看Readme文件

**Comment by ghost** [comment]
ValueError: Shape of variable bert/embeddings/LayerNorm/beta:0 ((128,)) doesn't match with shape of tensor bert/embeddings/LayerNorm/beta ([312]) from checkpoint reader.

**Comment by ghost** [comment]
官方ALBert项目中下的modeling.py   是哪个官方？google还是？

**Comment by ghost** [comment]
已解决。
